@extends('layouts.app')

@section('title', 'Create a Case')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <h1 class="mb-4">Create a Case</h1>
                <form action="{{ route('complaints.store') }}" method="POST" enctype="multipart/form-data"
                      id="complaintForm">
                    @csrf
                    <input type="hidden" name="anonymous" value="1">

                    <div id="userInfoFields">
                        <div class="card mb-4">
                            <div class="card-body">
                                <h5 class="card-title">Victim Information</h5>
                                <div class="mb-3">
                                    <label for="first_name" class="form-label">First Name</label>
                                    <input type="text" class="form-control" id="first_name" name="first_name" value="{{ old('first_name') }}" required>
                                </div>
                                <div class="mb-3">
                                    <label for="last_name" class="form-label">Last Name</label>
                                    <input type="text" class="form-control" id="last_name" name="last_name" value="{{ old('last_name') }}" required>
                                </div>
                                <div class="mb-3">
                                    <label for="phone" class="form-label">Phone Number</label>
                                    <input type="tel" class="form-control" id="phone" name="phone" value="{{ old('phone') }}" required>
                                </div>
                                <div class="mb-3">
                                    <label for="email" class="form-label">Email Address</label>
                                    <input type="email" class="form-control" id="email" name="email" value="{{ old('email') }}" required>
                                </div>
                                <div class="mb-3">
                                    <div class="form-check">
                                        <input class="form-check-input" type="checkbox" id="autogenerated_password" name="autogenerated_password" checked>
                                        <label class="form-check-label" for="autogenerated_password">
                                            Auto Generated Password
                                        </label>
                                    </div>
                                </div>
                                <div class="mb-3" id="passwordField" style="display: none;">
                                    <label for="password" class="form-label">Password</label>
                                    <input type="password" class="form-control" id="password" name="password" value="{{ old('password') }}">
                                </div>
                            </div>
                            <div class="card-body">
                                <h5 class="card-title">Address Information</h5>
                                <div class="mb-3">
                                    <label for="address" class="form-label">Address</label>
                                    <input type="text" class="form-control" id="address" name="address" value="{{ old('address') }}">
                                </div>
                                <div class="mb-3">
                                    <label for="city" class="form-label">City</label>
                                    <input type="text" class="form-control" id="personCity" name="person_city" value="{{ old('person_city') }}">
                                </div>
                                <div class="mb-3">
                                    <label for="state" class="form-label">State</label>
                                    <input type="text" class="form-control" id="personState" name="person_state" value="{{ old('person_state') }}">
                                </div>
                                <div class="mb-3">
                                    <label for="zip" class="form-label">Zip Code</label>
                                    <input type="text" class="form-control" id="zip" name="zip" value="{{ old('zip') }}">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">Defendant Information</h5>
                            <div class="mb-3">
                                <label for="first_name" class="form-label">Name</label>
                                <input type="text" class="form-control" id="officer_name" name="officer_name" value="{{ old('officer_name') }}" required>
                            </div>
                            <div class="mb-3">
                                <label for="first_name" class="form-label">Phone Number</label>
                                <input type="text" class="form-control" id="officer_badge_number" name="officer_badge_number" value="{{ old('officer_badge_number') }}" required>
                            </div>
                        </div>
                    </div>

                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">Case Details</h5>
                            <div class="mb-3">
                                <label for="description" class="form-label">Description</label>
                                <textarea class="form-control" id="description" name="description" rows="5" required>{{ old('description') }}</textarea>
                            </div>
                            <div class="mb-3">
                                <label for="incident_date" class="form-label">Filing Date</label>
                                <input type="datetime-local" class="form-control" id="incident_date" name="incident_date" value="{{ old('incident_date') }}" required>
                            </div>
                            <div class="mb-3">
                                <label for="court_name" class="form-label">Court Name</label>
                                <input type="text" class="form-control" id="court_name" name="court_name" value="{{ old('court_name') }}" required>
                            </div>
                        </div>
                    </div>

                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">Criminal Charges</h5>
                            <div id="witnesses" class="row">
                                <div class="witness row mb-3">
                                    <div class="witness mb-3 col-md-7">
                                        <label for="witness_name_0" class="form-label">Charge</label>
                                        <input type="text" class="form-control" id="witness_name_0" name="witnesses[0][name]" value="{{ old('witnesses.0.name') }}">
                                    </div>
                                    <div class="witness mb-3 col-md-5">
                                        <label for="witness_contact_0" class="form-label">Docket Number</label>
                                        <input type="tel" class="form-control" id="witness_contact_0" name="witnesses[0][contact]" value="{{ old('witnesses.0.contact') }}">
                                    </div>
                                </div>
                            </div>
                            <button type="button" class="btn btn-secondary" id="addWitness">Add Another Charge</button>
                        </div>
                    </div>

                    <div class="card mb-4">
                        <div class="card-body">
                            <h5 class="card-title">Attachments</h5>
                            <div class="mb-3">
                                <label for="attachments" class="form-label">Upload Files (Images, Videos, Documents)</label>
                                <input type="file" class="form-control" id="attachments" name="attachments[]" multiple>
                            </div>
                        </div>
                    </div>

                    <div class="text-center">
                        <button type="submit" class="btn btn-primary btn-lg">Submit Report</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <style>
        .card {
            border-radius: 10px;
            background-color: #ffffff;
        }

        .form-check-input {
            width: 16px;
            height: 16px;
        }
    </style>

    <script>
        let witnessIndex = 1;
        document.getElementById('addWitness').addEventListener('click', function() {
          const witnessesDiv = document.getElementById('witnesses');
          const newWitnessDiv = document.createElement('div');
          newWitnessDiv.classList.add('witness', 'row', 'mb-3');
          newWitnessDiv.innerHTML = `
                <div class="witness mb-3 col-md-6">
                    <label for="witness_name_${witnessIndex}" class="form-label">Charge</label>
                    <input type="text" class="form-control" id="witness_name_${witnessIndex}" name="witnesses[${witnessIndex}][name]">
                </div>
                <div class="witness mb-3 col-md-5">
                    <label for="witness_contact_${witnessIndex}" class="form-label">Docket Number</label>
                    <input type="tel" class="form-control" id="witness_contact_${witnessIndex}" name="witnesses[${witnessIndex}][contact]">
                </div>
                <div class="col-md-1 d-flex align-items-center justify-content-center">
                    <button type="button" class="btn btn-danger delete-witness">Delete</button>
                </div>
            `;
          witnessesDiv.appendChild(newWitnessDiv);
          witnessIndex++;
        });

        document.getElementById('witnesses').addEventListener('click', function(event) {
          if (event.target.classList.contains('delete-witness')) {
            event.target.closest('.witness').remove();
          }
        });

        document.getElementById('autogenerated_password').addEventListener('change', function() {
          const passwordField = document.getElementById('passwordField');
          if (this.checked) {
            passwordField.style.display = 'none';
          } else {
            passwordField.style.display = 'block';
          }
        });
    </script>
@endsection

@if ($errors->any())
    <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
@endif
